project_name: variant
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/variantdev/go-actions/cmd.VERSION={{.Version}}
  main: ./cmd
  binary: actions
changelog:
  filters:
    # commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - '^docs:'
      - typo
