name: dev

# See https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events
on:
  check_run:
    types:
    - created
    - rerequested
    - completed
    - requested_action
  check_suite:
    types:
    - completed
    - requested
    - rerequested
  pull_request:
    types:
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - closed
    - reopened
    - synchronize
    - ready_for_review
    - locked
    - unlocked
    - review_requested
    - review_request_removed
jobs:
  run-example:
    if: startsWith(github.repository, 'variantdev/')
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.7'
    - run: |
        make build
        bin/actions checks -create-run devrun -run devrun -- bin/actions pullvet -require-any -label releasenote/none -note releasenote
