name: dev

# See https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events
on:
#  check_run:
#    types:
#    - created
#    - rerequested
#    - completed
#    - requested_action
#  check_suite:
#    types:
#    - completed
#    - requested
#    - rerequested
  pull_request:
    types:
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
#    - closed
    - reopened
    - synchronize
    - ready_for_review
    - locked
    - unlocked
    - review_requested
    - review_request_removed
jobs:
  ensure-dev1:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'variantdev/')
    steps:
    - run: |
        echo GITHUB_ACTION: $GITHUB_ACTION
        echo GITHUB_WORKFLOW: $GITHUB_WORKFLOW
        echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
        echo GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH
        cat $GITHUB_EVENT_PATH
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.7'
    - run: |
        make build
    - name: dev1
      run: |
        bin/actions checks -run dev1 -- bin/actions pullvet -require-any -label dev1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ensure-dev2:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'variantdev/')
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.7'
    - run: |
        make build
    - name: dev2
      run: |
        bin/actions checks -run dev2 -- bin/actions pullvet -require-any -label dev2 -label dev3
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ensure-dev3:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'variantdev/')
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.7'
    - run: |
        make build
    - name: dev3
      run: |
        bin/actions checks -status-context checks/dev3 -- bin/actions pullvet -require-any -label dev3
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ensure-changelog:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'variantdev/')
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.12.7'
    - run: |
        make build
    - name: changelog
      run: |
        bin/actions checks -status-context checks/changelog -- bin/actions pullvet -require-any -note changelog1 -note changelog2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ensure-releasenote:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'variantdev/')
    steps:
    - uses: docker://variantdev/actions:latest
      with:
        entrypoint: sh
        args: -c 'actions checks -status-context checks/releasenote -- actions pullvet -require-any -label releasenote/none -note releasenote'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
